/** Russian for every English text the app shows; the English text is the key. */
export const RU: Record<string, string> = {
  // Pages, sections, headings
  Overview: 'Обзор',
  Wall: 'Стена',
  Sessions: 'Сессии',
  Usage: 'Расход',
  Settings: 'Настройки',
  Session: 'Сессия',
  Panes: 'Панели',
  'Running in other folders': 'Работают в других папках',
  'Sessions of {folder}': 'Сессии {folder}',
  'Subscription limits': 'Лимиты подписок',
  'Most tokens': 'Больше всего токенов',
  Preview: 'Предпросмотр',
  Keys: 'Клавиши',
  'New pane': 'Новая панель',
  'in {folder}': 'в {folder}',
  'by CLI': 'по CLI',
  'kept in {file}': 'хранятся в {file}',
  'Brainyard needs at least {size}': 'Brainyard нужно не меньше {size}',

  // What a CLI or a session does
  ready: 'готов',
  'sign in': 'войти',
  limited: 'лимит',
  unknown: 'неизвестно',
  'not installed': 'не установлен',
  error: 'ошибка',
  'signed in': 'вход выполнен',
  'sign-in not confirmed': 'вход не подтверждён',
  'checking…': 'проверяю…',
  'reading…': 'читаю…',
  'reading the screen…': 'читаю экран…',
  working: 'работает',
  waiting: 'ждёт',
  idle: 'простаивает',
  open: 'открыта',
  'full screen': 'на весь экран',
  saved: 'сохранена',
  active: 'активна',
  quiet: 'тихо',
  'quiet {ago}': 'тихо {ago}',
  now: 'сейчас',
  '{ago} ago': '{ago} назад',
  '(no label)': '(без метки)',
  '(untitled)': '(без названия)',
  'open in another terminal': 'открыта в другом терминале',

  // Limits and usage
  weekly: 'неделя',
  monthly: 'месяц',
  rolling: 'скользящее',
  'reset since seen': 'сброшено с тех пор',
  resetting: 'сбрасывается',
  'resets in {time}': 'сброс через {time}',
  'seen {ago} ago': 'данные {ago} назад',
  'limits: checking…': 'лимиты: проверяю…',
  'not checked': 'не проверялись',
  'not seen yet: /usage in Claude Code shows them': 'ещё не видны: их показывает /usage в Claude Code',
  'cached for another account': 'сохранены для другого аккаунта',
  'OpenCode Go is not connected': 'OpenCode Go не подключён',
  tokens: 'токенов',
  used: 'расход',
  in: 'вход',
  out: 'выход',
  cache: 'кеш',
  cost: 'стоимость',
  total: 'итого',
  sessions: 'сессий',
  'no price': 'без цены',
  'unknown model': 'неизвестная модель',
  'nothing counted here yet': 'здесь пока ничего не посчитано',

  // The session card
  folder: 'папка',
  started: 'начата',
  updated: 'обновлена',
  'nothing selected': 'ничего не выбрано',
  'into its pane': 'в её панель',
  'close the pane': 'закрыть панель',
  'stop it: the conversation stays': 'остановить: разговор останется',
  or: 'или',
  'continue it in a pane': 'продолжить в панели',

  // Empty places
  'panes need tmux': 'панелям нужен tmux',
  'panes need tmux: brew install tmux': 'панелям нужен tmux: brew install tmux',
  'panes need tmux, which Windows does not have': 'панелям нужен tmux, а в Windows его нет',
  'panes need tmux: the wall shows their screens': 'панелям нужен tmux: стена показывает их экраны',
  'no panes yet · n starts one': 'панелей пока нет · n запускает новую',
  'no panes yet · n starts one here': 'панелей пока нет · n запускает новую прямо здесь',
  'no sessions in this folder yet · n starts one': 'в этой папке сессий пока нет · n запускает новую',
  'no sessions yet': 'сессий пока нет',
  'nothing fits the filter · Esc clears it': 'под фильтр ничего не подходит · Esc сбрасывает',

  // The wall
  'i type · Enter full screen': 'i печатать · Enter на весь экран',
  '✎ typing · Ctrl+Q back': '✎ ввод · Ctrl+Q назад',
  'Ctrl+Q — back to Brainyard': 'Ctrl+Q — назад в Brainyard',
  '↑ {rows} rows back · the wheel down returns': '↑ на {rows} строк назад · колесо вниз — обратно',
  'screen {page}/{pages}': 'экран {page}/{pages}',
  'in focus': 'в фокусе',
  typing: 'ввод',
  'waits for you': 'ждёт вас',

  // Keys
  'go in (Ctrl+Q back)': 'войти (Ctrl+Q назад)',
  'go in': 'войти',
  'new {brain} pane': 'новая панель {brain}',
  close: 'закрыть',
  stop: 'остановить',
  'continue in a pane': 'продолжить в панели',
  choose: 'выбрать',
  start: 'запустить',
  cancel: 'отмена',
  yes: 'да',
  'any other key': 'любая другая клавиша',
  no: 'нет',
  'any key': 'любая клавиша',
  back: 'назад',
  new: 'новая',
  help: 'справка',
  quit: 'выход',
  focus: 'фокус',
  type: 'печатать',
  zoom: 'развернуть',
  'all tiles': 'все плитки',
  'typing into the tile: every key goes to its CLI': 'ввод в плитку: все клавиши уходят её CLI',
  filter: 'фильтр',
  'type to filter': 'печатайте для фильтра',
  'keep it': 'оставить',
  'clear it': 'сбросить',
  move: 'выбор',
  'change, kept at once': 'изменить, сохраняется сразу',

  // Help
  'pages: overview, wall, sessions, usage, settings': 'страницы: обзор, стена, сессии, расход, настройки',
  'move · the next section; PgUp PgDn, Home End': 'выбор · следующий раздел; PgUp PgDn, Home End',
  'into the pane, full screen; Ctrl+Q — back': 'в панель на весь экран; Ctrl+Q — назад',
  'on an agent — a new pane; on a saved session — continue it':
    'на агенте — новая панель; на сохранённой сессии — продолжить её',
  'a new pane · close the pane (the conversation stays)': 'новая панель · закрыть панель (разговор останется)',
  'stop a background session · continue a session in a pane': 'остановить фоновую сессию · продолжить сессию в панели',
  "the panes' live screens side by side": 'живые экраны панелей рядом',
  'the tile in focus': 'плитка в фокусе',
  'type into it: every key goes to its CLI until Ctrl+Q': 'печатать в неё: все клавиши уходят её CLI до Ctrl+Q',
  'full screen; Ctrl+Q — back to the wall': 'на весь экран; Ctrl+Q — назад на стену',
  'zoom the tile · grid, main and stack, columns · more panes':
    'развернуть плитку · сетка, главная и стопка, колонки · другие панели',
  "a new tile, ready to type into · close the tile's pane": 'новая плитка сразу с вводом · закрыть панель плитки',
  '/ filters; Enter or r continues, s stops, x closes its pane':
    '/ — фильтр; Enter или r продолжает, s останавливает, x закрывает её панель',
  '↑↓ choose, ←→ change: language, theme, accent, layout, bell, first page':
    '↑↓ выбор, ←→ изменить: язык, тема, акцент, раскладка, звонок, первая страница',
  'read everything again': 'перечитать всё',
  'Click  wheel': 'Щелчок  колесо',
  'in a browser: a click selects, a double click is Enter, the wheel moves':
    'в браузере: щелчок выбирает, двойной щелчок — Enter, колесо двигает',
  'quit: the panes keep running': 'выход: панели продолжают работать',
  'Panes are CLI sessions in tmux (tmux -L brainyard): they outlive this app and this terminal.':
    'Панели — это сессии CLI в tmux (tmux -L brainyard): они переживают и приложение, и терминал.',
  'Limits come without a paid call: Claude Code’s are the ones its /usage fetched last.':
    'Лимиты — без платных вызовов: у Claude Code это то, что последним получил его /usage.',

  // Settings
  Language: 'Язык',
  Theme: 'Тема',
  Accent: 'Акцент',
  'Wall layout': 'Раскладка стены',
  'Bell when an agent waits': 'Звонок, когда агент ждёт',
  'Open on': 'Открывать на',
  terminal: 'терминал',
  ocean: 'океан',
  ember: 'угли',
  forest: 'лес',
  contrast: 'контраст',
  mono: 'моно',
  theme: 'как в теме',
  cyan: 'бирюзовый',
  blue: 'синий',
  magenta: 'пурпурный',
  green: 'зелёный',
  yellow: 'жёлтый',
  orange: 'оранжевый',
  pink: 'розовый',
  violet: 'фиолетовый',
  grid: 'сетка',
  main: 'главная',
  columns: 'колонки',
  on: 'вкл',
  off: 'выкл',
  'Your own colours: "colors": {"accent": "#ff8700"} in the file — hex, or a number of the 256.':
    'Свои цвета: "colors": {"accent": "#ff8700"} в файле — hex или номер из 256.',

  // Notes and questions
  'starting {cli}…': 'запускаю {cli}…',
  'continuing in {cli}…': 'продолжаю в {cli}…',
  'settings not kept: {reason}': 'настройки не сохранились: {reason}',
  'closed {pane} · what was said in it stays: r continues it from Sessions':
    'закрыта {pane} · сказанное в ней осталось: r продолжит её из «Сессий»',
  '{pane} has already ended': '{pane} уже завершилась',
  'stopping {id}…': 'останавливаю {id}…',
  'stopped {id} · its conversation stays: r continues it in a pane':
    'остановлена {id} · разговор остался: r продолжит его в панели',
  '{id} has already stopped': '{id} уже остановлена',
  '{cli} is not installed': '{cli} не установлен',
  'Close {pane}? Its CLI ends; what was said in it stays, and r continues it.':
    'Закрыть {pane}? Её CLI завершится; сказанное останется, и r продолжит.',
  'Stop {id}{title}? It stops working; the conversation stays.':
    'Остановить {id}{title}? Работа прервётся; разговор останется.',
  'no tile to type into: n starts one': 'нет плитки для ввода: n запускает новую',
  'no CLI is installed: brainyard status says how to install one':
    'ни один CLI не установлен: brainyard status подскажет, как установить',
  'it runs in the background: s stops it, then r continues it here':
    'она работает в фоне: s останавливает, потом r продолжит её здесь',
  'it is open in another terminal: continue it there, or end it there and r continues it here':
    'она открыта в другом терминале: продолжите там или завершите её там, и r продолжит здесь',
  'x closes a pane: select one under Panes': 'x закрывает панель: выберите её в «Панелях»',
  'a pane is closed with x: its CLI ends, the conversation stays':
    'панель закрывается клавишей x: CLI завершится, разговор останется',
  's stops a {cli} background session; this is not one': 's останавливает фоновую сессию {cli}; эта — не фоновая',
  'r continues a saved session: select one under Sessions': 'r продолжает сохранённую сессию: выберите её в «Сессиях»',
};
